### ISSUE TITLE
Something wrong with main.py at line 284?

### ISSUE THREAD

**Issue by Sagiring** [ICE27182/Python-3D-renderer#3]
![image](https://github.com/ICE27182/Python-3D-renderer/assets/102647163/728fffe5-61ff-46b2-9edf-2256e8fce20a)

**Comment by Sagiring** [comment]
Missing an r?

**Comment by ICE27182** [comment]
Yeah, I guess. Haven't touched main.py for a long time and the files are pretty messy indeed. If you want to run the project, try Readability/prefinal.py
