### ISSUE TITLE
from_bytes() missing required argument 'byteorder' (pos 2)

### ISSUE THREAD

**Issue by rollingQP** [ICE27182/Python-3D-renderer#4]
Hi, I frequently got the error

> in get_image_properties
>     self.width = int.from_bytes(self.bin[16:20])
> TypeError: from_bytes() missing required argument 'byteorder' (pos 2)

I think the reason for that could be the differences between Python versions, and in your version of Python, 'byteorder' might be an optional argument. I am currently using Python 3.10.11 on Windows. Could you specify which version are you using?

**Comment by ICE27182** [comment]
Yes, I think it is due to the Python version difference. 
I am using Python 3.11.4 and I replicated the error by executing the program with Python 3.9.13.
You may fix this error by adding byteorder="big" argument to every int.from_byte method in png.py, or you may re-pull from this repository.
