### ISSUE TITLE
You should not upload the ".vscode" and "__pycache__" folders

### ISSUE THREAD

**Issue by sxxyrry** [ICE27182/Python-3D-renderer#5]
You should not upload the ".vscode" and "__pycache__" folders

**Comment by ICE27182** [comment]
Thanks. Forgot to untrack them. It should be fixed now.

**Comment by LaoshuBaby** [comment]
> You should not upload the ".vscode"

It's not strictly unnecessary to upload the ".vscode" editor settings. It's generally more advisable to utilize ".editorconfig" for managing code formatting across different editors. This approach primarily helps in preventing auto-formatting issues, which, while not significantly impactful for Python, is particularly useful for managing JavaScript code. （For Python, it is recommended to use Black for formatting files.） ~~Essentially, whether or not to upload ".vscode" depends on specific circumstances and needs of project management.~~

**Comment by ICE27182** [comment]
Thanks for the information
