### ISSUE TITLE
[WIP] POSIX support

### ISSUE THREAD

**Issue by litlighilit** [ICE27182/Python-3D-renderer#6]
Currently I'm adding support for POSIX,

on this forked [repo](https://github.com/litlighilit/Python-3D-renderer),

and it seems every Windows-only function has been implemented for other UNIX systems.

However, when I tested on Linux, the pixes were just rowing in chaos!

Maybe something wrong with the `get_terminal_size`?

**Comment by ICE27182** [comment]
Apologies for the delayed response. I've been pretty occupied lately.

First, try pressing "r" on your keyboard to refresh the screen, which may resolve a supposingly terminal-related problem that can cause this issue you described.

If that does not resolve your problem, then, unfortunately, you may need to explore alternative approaches. According to python docs (https://docs.python.org/3/library/os.html#querying-the-size-of-a-terminal), os.get_terminal_size is only available on Unix and Windows. While I am not planning to work on this project in the near future, you may need to find another means that works well on linux by yourself.

Should you failed to find another method to retrieve the width and height information, consider letting the user decide what resolution they would like to have at the beginning of the program, or enabling the user to alter the resolution at run-time. For example, you could integrate this functionality into the command-line interface in prefinal.py and pymain.py, or assign certain keys to adjust the horizontal and vertical resolution, among other options.

**Comment by litlighilit** [comment]
> os.get_terminal_size is only available on Unix and Windows. While I am not planning to work

Linux is of UNIX   :)


And, I've altered to use [`shutil.get_terminal_size`](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size), which will look up environment variable `COLUMNS` and `LINES` firstly.

**Comment by litlighilit** [comment]
I'll try if predefined COLUMNS and LINES env help.
